### ISSUE TITLE
Will you release UCI datasets experiment codes?

### ISSUE THREAD

**Issue by jueliangguke** [ssydasheng/FBNN#1]

**Comment by ssydasheng** [comment]
will in one week.

**Comment by jueliangguke** [comment]
> will in one week.

thanks.

**Comment by ssydasheng** [comment]
Added Regression Codes for Small Datasets. Btw, I also recommend you to check a new ICML paper [https://github.com/thjashin/gp-infer-net](url), which implements FBNN and their proposed GPNet using Explicit Posteriors, including Random Feature, Neural Tangent Kernel and etc.
